(cl:in-package imagenex831l-msg)
(cl:export '(HEADER-VAL
          HEADER
          INTENSITY-VAL
          INTENSITY
          RANGE_ERROR-VAL
          RANGE_ERROR
          FREQUENCY_ERROR-VAL
          FREQUENCY_ERROR
          INTERNAL_ERROR-VAL
          INTERNAL_ERROR
          SWITCHES_ACCEPTED-VAL
          SWITCHES_ACCEPTED
          HEAD_POSITION-VAL
          HEAD_POSITION
          STEP_DIRECTION-VAL
          STEP_DIRECTION
          MAX_RANGE-VAL
          MAX_RANGE
          PROFILE_RANGE-VAL
          PROFILE_RANGE
          ROLL_ANGLE-VAL
          ROLL_ANGLE
          PITCH_ANGLE-VAL
          PITCH_ANGLE
          ROLL_ACCELERATION-VAL
          ROLL_ACCELERATION
          PITCH_ACCELERATION-VAL
          PITCH_ACCELERATION
))